name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Pull latest code (or clone if not done)
            cd ~/my-node-app || (git clone https://github.com/avashokkumar/ekcontent.git ~/my-node-app && cd ~/my-node-app)

            git pull origin main

            # Install dependencies
            npm install

            # Optional: build (if using React or TS)
            # npm run build

            # Restart the app (using pm2 or node)
            pm2 restart app || pm2 start index.js --name app
          EOF
